### ISSUE TITLE
Instructor Hello World code hangs with Gemini Flash

### ISSUE THREAD

**Issue by delip** [jxnl/instructor#817] opened 2024-07-09 04:06 UTC
- [x] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [x] Other gemini-1.5-flash

**Describe the bug**
```
instructor                    1.3.4
google-ai-generativelanguage  0.6.6
google-generativeai           0.7.2
```

```
Python 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]
```

**To Reproduce**
Run this sample code:
```Python
import instructor
import google.generativeai as genai
from pydantic import BaseModel


class User(BaseModel):
    name: str
    age: int


client = instructor.from_gemini(
    client=genai.GenerativeModel(
        model_name="models/gemini-1.5-flash",
    ),
    mode=instructor.Mode.GEMINI_JSON,
)

# note that client.chat.completions.create will also work
resp = client.messages.create(
    messages=[
        {
            "role": "user",
            "content": "Extract Jason is 25 years old.",
        }
    ],
    response_model=User,
)

assert isinstance(resp, User)
assert resp.name == "Jason"
assert resp.age == 25
```

The code just hangs.

**Comment by ivanleomk** [comment] 2024-07-13 16:39
Hey @delip, I just tried using your code snippet above and couldn't seem to reproduce the error.  I tested it using `uv` and installed the packages in a fresh environment.

```bash
(instructor) ivanleo@Ivans-MacBook-Pro instructor % uv pip list | grep -E 'instructor|google-ai-generativelanguage|google-generativeai'
google-ai-generativelanguage 0.6.6   
google-generativeai          0.7.2   
instructor                   1.3.4   
(instructor) ivanleo@Ivans-MacBook-Pro instructor % python3 --version
Python 3.11.9
(instructor) ivanleo@Ivans-MacBook-Pro instructor % python3 test.py
name='Jason' age=25
(instructor) ivanleo@Ivans-MacBook-Pro instructor % 
```

Are you still facing this issue?

**Comment by ivanleomk** [comment] 2024-07-17 00:11
Closing this issue for now due to lack of activty but feel free to re-open it if you're still facing the same issue! :)

**Closed by ivanleomk** 2024-07-17 00:11 UTC
