### ISSUE TITLE
Sudden error: openai.BadRequestError: Error code: 400 - Invalid schema for function

### ISSUE THREAD

**Issue by zahra-rou** [jxnl/instructor#961] opened 2024-08-27 17:41 UTC
- This is actually a bug report.
- I have tried searching the documentation and have not found an answer.

**What Model are you using?**
- gpt-4o 

**Describe the bug**
Today, all of a sudden our app crashed when sending a request to the GPT model. In our request, we are using a Pydantic class called Datasets, which has a nested structure. It contains multiple classes as attributes.
Everything was working perferctly fine till yesterday, but suddenly without making any changes to packages, it has stopped working. 
When I was trying to debug the problem, I noticed if I change the type of one of the attributes in my Pydantic classes to be a different type than Union, it doesn't give the error anymore. But still I need to have the Union. Removing that has caused other side effects. 

This is part of the error we get:
ERROR - [app.py] RetryError[<Future at 0x167d3d9d0 state=finished raised BadRequestError>]
...
raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid schema for function 'Datasets'. Please ensure it is a valid JSON Schema.", 'type': 'invalid_request_error', 'param': 'tools[0].function.parameters', 'code': 'invalid_function_parameters'}}
...
raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x167d3d9d0 state=finished raised BadRequestError>]
...
 raise InstructorRetryException(
instructor.exceptions.InstructorRetryException: RetryError[<Future at 0x167d3d9d0 state=finished raised BadRequestError>]

**Expected behavior**
No error in the response.

The request to the model:

openai_instructor_client = instructor.from_openai(
            openai.AzureOpenAI(
                azure_ad_token_provider=bearer_token_provider,
                azure_endpoint=azure_endpoint,
                api_version=api_version,
            )
        )
response: ChatCompletion = (
                    openai_instructor_client.chat.completions.create(
                        model=model_name,
                        messages=messages,
                        temperature=temperature,
                        response_model=Datasets,
                        max_retries=max_retries
                    )
                )

**Comment by ivanleomk** [comment] 2024-08-28 01:46
Hey @zahra-rou could you provide a code reproduction of the Datasets class? I can take a look at it and see what's happening here

**Comment by zahra-rou** [comment] 2024-08-28 05:27
@ivanleomk 
Thanks for your response. Here are my Pydantic Classes:

from pydantic import BaseModel, Field, ConfigDict, model_validator
from typing import List, Optional, Literal, Union

class Dataset(BaseModel):
    name: Literal[
        "aaa", "bbb", "ccc", "ddd", "eee"
    ] = Field(
        description="The name of the dataset can be any of the names in this list: aaa, bbb, ccc, ddd, eee"
    )
    params: Union[
        aaaParams,
        bbbParams,
        cccParams,
        dddParams,
        eeeParams,
    ] = Field(
        description="""The value of params is defined based on the name of the dataset. 
        If the name of the dataset is aaa, the params should be aaaParams, 
        if it's bbb, the params should be bbbParams, 
        if it's ccc, the params should be cccParams, 
        if it's ddd, the params should be dddParams,
        if it's eee, the params should be eeeParams.
        """
    )

    @model_validator(mode="before")
    @classmethod
    def validate_params(cls, values):
        dataset_name = values.get("name")
        params = values.get("params")

        if dataset_name == "aaa" and not isinstance(
            params, aaaParams
        ):
            values["params"] = aaaParams.model_validate(params)
        elif dataset_name == "bbb" and not isinstance(
            params, bbbParams
        ):
            values["params"] = bbbParams.model_validate(params)
        elif dataset_name == "ccc" and not isinstance(
            params, cccParams
        ):
            values["params"] = cccParams.model_validate(params)
        elif dataset_name == "ddd" and not isinstance(params, dddParams):
            values["params"] = dddParams.model_validate(params)
        elif dataset_name == "eee" and not isinstance(
            params, eeeParams
        ):
            values["params"] = eeeParams.model_validate(
                params
            )

        return values

----------------------
class Datasets(BaseModel):
    datasets: List[Dataset] = Field(description="Collection of datasets.")

----------------------
Each of the dataset classes have their own set of attributes, for instance:

class aaaParams(BaseModel):

    model_config = ConfigDict(extra="forbid")

    att_1: Optional[str] | None = Field(
        description="att_1 is a string value that indicates ... . This value can be None as well.",
        default=None,
    )
    att_2: Optional[str] | None = Field(
        description="att_2 is a string value that indicates ... . This value can be None as well.",
        default=None,
    )
    att_3: List[str] = Field(description="A list of ..., default=[])

**Comment by onejgordon** [comment] 2024-08-31 15:39
I'm seeing an identical error using 4o and Mode.TOOLS_STRICT. It was resolved by removing all use of default args in my classes' Field definitions. Perhaps a problem in the instructor schema filtering? 

Would love to revert to use field defaults.

**Comment by ivanleomk** [comment] 2024-08-31 15:45
@onejgordon just took a look at the error, I believe it's because OpenAI's Structured Outputs mode ( which we implemented using TOOLS_STRICT)  doesn't support the default field property. You can throw the error with the following code which uses their native sdk.

```python
import openai
from pydantic import BaseModel, Field

client = openai.OpenAI()


class User(BaseModel):
    name: str
    age: str
    is_admin: bool = Field(default=False)


resp = client.beta.chat.completions.parse(
    model="gpt-4o-mini",
    messages=[
        {
            "role": "user",
            "content": "Ivan is a 27 year old software engineer in Singapore",
        }
    ],
    response_format=User,
)

print(resp)
```

**Comment by ivanleomk** [comment] 2024-08-31 15:49
@zahra-rou are you using TOOLS or TOOLS_STRICT in your current application btw?

**Comment by onejgordon** [comment] 2024-08-31 19:37
Thanks for the response @ivanleomk. What are the implications of switching back to TOOLS from TOOLS_STRICT? I was under the impression that to get the guaranteed schema compliance from OpenAI via instructor, we need to use the TOOLS_STRICT mode.

**Comment by jxnl** [comment] 2024-09-02 00:43
> Thanks for the response @ivanleomk. What are the implications of switching back to TOOLS from TOOLS_STRICT? I was under the impression that to get the guaranteed schema compliance from OpenAI via instructor, we need to use the TOOLS_STRICT mode.

your evals should tell you your error rates.

**Closed** 2024-09-23 17:39 UTC
