### ISSUE TITLE
No module named 'tenacity.asyncio'

### ISSUE THREAD

**Issue by axfrl** [jxnl/instructor#766] opened 2024-06-17 10:07 UTC
- [x] This is actually a bug report.

Hello,
I try to import instructor 1.3.3 in my notebook run on an azure cluster(spark 3.5, scala 2.12).
I have the latest openai library (1.34.0). 

I always have this error message:
ModuleNotFoundError: No module named 'tenacity.asyncio'
[...]
-->653 from tenacity.asyncio import AsyncRetrying  # noqa:E402,I100

**Comment by rishav1122** [comment] 2024-06-17 13:01
yeah, same error
I have also installed tenacity 8.4.0

**Comment by fer-git** [comment] 2024-06-17 13:49
I think the issue is on tenacity here, you need to update it to 8.4.1
[https://github.com/jd/tenacity/releases/tag/8.4.1](https://github.com/jd/tenacity/releases/tag/8.4.1)

**Comment by ivanleomk** [comment] 2024-07-13 16:47
@fer-git thanks for catching this, managed to reproduce this issue. I'll try to publish a fix soon for this

```
(instructor) ivanleo@Ivans-MacBook-Pro instructor % uv pip install tenacity==8.4.0                               
Resolved 1 package in 30ms
Installed 1 package in 2ms
 - tenacity==8.4.1
 + tenacity==8.4.0
(instructor) ivanleo@Ivans-MacBook-Pro instructor % python3 test.py                                              
Traceback (most recent call last):
  File "/Users/ivanleo/Documents/coding/instructor/test.py", line 1, in <module>
    import instructor
  File "/Users/ivanleo/Documents/coding/instructor/instructor/__init__.py", line 15, in <module>
    from .patch import apatch, patch
  File "/Users/ivanleo/Documents/coding/instructor/instructor/patch.py", line 17, in <module>
    from instructor.retry import retry_async, retry_sync
  File "/Users/ivanleo/Documents/coding/instructor/instructor/retry.py", line 18, in <module>
    from tenacity import AsyncRetrying, RetryError, Retrying, stop_after_attempt
  File "/Users/ivanleo/Documents/coding/instructor/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 653, in <module>
    from tenacity.asyncio import AsyncRetrying  # noqa:E402,I100
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tenacity.asyncio'
(instructor) ivanleo@Ivans-MacBook-Pro instructor % uv pip install tenacity==8.4.1
Resolved 1 package in 1ms
Installed 1 package in 2ms
 - tenacity==8.4.0
 + tenacity==8.4.1
(instructor) ivanleo@Ivans-MacBook-Pro instructor % python3 test.py               
name='Jason' age=25
```

**Comment by ivanleomk** [comment] 2024-07-17 00:10
@fer-git tenacity is now set to min 8.4.1 in instructor 1.3.5 so closing this issue!

**Closed by ivanleomk** 2024-07-17 00:10 UTC
